# Generated by Django 5.0.6 on 2024-05-26 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_remove_personne_email_remove_personne_fisrtname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='photo',
        ),
    ]
