# Generated by Django 4.2.14 on 2024-07-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_remove_personne_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('Sexe', models.CharField(max_length=100)),
                ('universite', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=100)),
                ('fac', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=100)),
            ],
        ),
    ]
