# Generated by Django 4.2.14 on 2024-07-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='email',
            field=models.CharField(default='vide', max_length=100),
            preserve_default=False,
        ),
    ]
